name: .NET Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        runtime: [win-x64, linux-x64, linux-arm64, osx-x64, osx-arm64]

    runs-on: ${{ matrix.runtime == 'win-x64' && 'windows-latest' || startsWith(matrix.runtime, 'osx-') && 'macos-latest' || 'ubuntu-latest' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore oChan.sln

    - name: Publish self-contained single-file executable
      run: |
        dotnet publish oChan.sln --configuration Release --output publish-output/${{ matrix.runtime }} -p:PublishSingleFile=true -p:SelfContained=true -r ${{ matrix.runtime }}

    - name: Create platform-specific zip
      run: |
        zip -r oChan-${{ matrix.runtime }}.zip publish-output/${{ matrix.runtime }}

    - name: Upload platform-specific zip artifacts
      uses: actions/upload-artifact@v3
      with:
        name: oChan-${{ matrix.runtime }}.zip
        path: oChan-${{ matrix.runtime }}.zip
        retention-days: 30

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all platform-specific zips
      uses: actions/download-artifact@v3
      with:
        path: build-artifacts

    - name: Create one big zip containing all platform zips
      run: |
        mkdir -p release-assets
        mv build-artifacts/* release-assets/
        cd release-assets
        zip -r oChan-all-platforms.zip *.zip

    - name: Upload big zip artifact
      uses: actions/upload-artifact@v3
      with:
        name: oChan-all-platforms.zip
        path: release-assets/oChan-all-platforms.zip
        retention-days: 30
