name: .NET Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        runtime: [win-x64, linux-x64, linux-arm64, osx-x64, osx-arm64]

    runs-on: ${{ matrix.runtime == 'win-x64' && 'windows-latest' || startsWith(matrix.runtime, 'osx-') && 'macos-latest' || 'ubuntu-latest' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Match your project's target framework

    - name: Restore dependencies
      run: dotnet restore oChan.sln  # Reference your oChan solution file

    - name: Publish self-contained single-file executable
      run: |
        dotnet publish oChan.sln --configuration Release --output publish-output/${{ matrix.runtime }} -p:PublishSingleFile=true -p:SelfContained=true -r ${{ matrix.runtime }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: oChan-${{ matrix.runtime }}
        path: publish-output/${{ matrix.runtime }}/
        retention-days: 30
